- bash_script/README.md
- bash_script/example_object_detection_tensorflow/get-model-object-detection-tf.sh
- bash_script/example_object_detection_tensorflow/meson.build
- bash_script/example_object_detection_tensorflow_lite/get-model-object-detection-tflite.sh
- bash_script/example_object_detection_tensorflow_lite/gst-launch-object-detection-tflite.sh
- bash_script/example_object_detection_tensorflow_lite/meson.build
- bash_script/meson.build
- meson.build
- native/example_cam/meson.build
- native/example_cam/nnstreamer_example_cam.c
- native/example_decoder_image_labelling/meson.build
- native/example_decoder_image_labelling/nnstreamer_example_decoder_image_labelling.c
- native/example_filter_performance_profile/meson.build
- native/example_filter_performance_profile/nnstreamer_example_filter_performance_profile.c
- native/example_image_classification/meson.build
- native/example_image_classification/nnstreamer_example_image_classification.c
- native/example_image_classification/nnstreamer_example_image_classification.py
- native/example_object_detection_tensorflow/meson.build
- native/example_object_detection_tensorflow/nnstreamer_example_object_detection_tf.cc
- native/example_object_detection_tensorflow_lite/meson.build
- native/example_object_detection_tensorflow_lite/nnstreamer_example_object_detection_tflite.cc
- native/example_sink/meson.build
- native/example_sink/nnstreamer_sink_example.c
- native/example_sink/nnstreamer_sink_example_play.c
- native/meson.build
- packaging/nnstreamer.manifest
- packaging/nnstreamer_example.spec
1. code clean and upload nnsteamer examples
2. add meson build
> [Example] upload examples

- native/example_image_classification/meson.build
update script to install python example
> [Meson] install python example

- bash_script/example_object_detection_tensorflow/get-model-object-detection-tf.sh
- bash_script/example_object_detection_tensorflow_lite/gst-launch-object-detection-tflite.sh
- meson.build
- native/example_cam/nnstreamer_example_cam.c
- native/example_decoder_image_labelling/nnstreamer_example_decoder_image_labelling.c
- native/example_image_classification/nnstreamer_example_image_classification.c
- native/example_image_classification/nnstreamer_example_image_classification.py
- native/example_object_detection_tensorflow/nnstreamer_example_object_detection_tf.cc
- native/example_object_detection_tensorflow_lite/nnstreamer_example_object_detection_tflite.cc
@mchehab requests to change scaler to videoconvert.
Also I update another changes for meson and script.
1. change to videoconvert instead videoscale
2. update dependency for thread
3. error to get tf model
> [Example] update changes - @open sesame 01/24 16:21 

- bash_script/example_object_detection_tensorflow_lite/gst-launch-object-detection-tflite.sh
the value of property `output1` of tflite-ssd has been changed at [PR#1052](https://github.com/nnsuite/nnstreamer/pull/1052) from nnstreamer
Signed-off-by: Hyoung Joo Ahn <hello.ahnn@gmail.com>
> [Bash/TFLite] update the script of the example: tflite-ssd - @open sesame 01/24 16:23

- README.md
This commit is to update the existing README.md file. 
> Documentation: update README.md - @open sesame 01/24 16:27

- bash_script/example_object_detection_tensorflow/gst-launch-object-detection-tf.sh
it works after the [pr #1069](https://github.com/nnsuite/nnstreamer/pull/1069) is merged
Signed-off-by: Hyoung Joo Ahn <hello.ahnn@gmail.com>
> [Bash] update the example script for tensorflow ssd model - @open sesame 1/28 19:50

- bash_script/example_object_detection_tensorflow/meson.build
to install the example updated meson script is needed
> [Bash] update the missed meson script to install

- android/README.md
This commit is to make a document to explain
how to build Android source code fully.
> Doc: Added how to build Android full source

- debian/rules
- meson.build
- packaging/nnstreamer-example.spec
add werror in project default options
> [Meson] add default werror option

- native/example_object_detection_tensorflow/nnstreamer_example_object_detection_tf.cc
- native/example_object_detection_tensorflow_lite/nnstreamer_example_object_detection_tflite.cc
generate proper error messages when the mandatory files are not valid
> [Native/TF] add proper error messages @open sesame - 03/06 08:42

- .github/CODEOWNERS
- .github/ISSUE_TEMPLATE.md
- .github/ISSUE_TEMPLATE/Bug_report.md
- .github/ISSUE_TEMPLATE/Feature_request.md
- .github/ISSUE_TEMPLATE/Support_request.md
- .github/PULL_REQUEST_TEMPLATE.md
This commit is to append template files such as issue, pull request,
and auto review list.
> github: Added template files

- native/example_object_detection_tensorflow_lite/nnstreamer_example_object_detection_tflite.cc
fix resolution of detected object in tf-lite ssd example
> [Example] fix resolution

- android/example_app/nnstreamer-ssd/AndroidManifest.xml
- android/example_app/nnstreamer-ssd/jni/nnstreamer-jni.c
- android/example_app/nnstreamer-ssd/jni/nnstreamer-ssd.cpp
- android/example_app/nnstreamer-ssd/res/layout/main.xml
- android/example_app/nnstreamer-ssd/res/values/strings.xml
- android/example_app/nnstreamer-ssd/src/org/freedesktop/gstreamer/nnstreamer/ssd/DownloadModel.java
- android/example_app/nnstreamer-ssd/src/org/freedesktop/gstreamer/nnstreamer/ssd/NNStreamerSSD.java
1. add code to download model files from aws.
2. activity lifecycle to play pipeline after resume state.
**Changelogs**
* Version 2:
- change download url
- change guide string to get models
- function name and ui-layout ids for clear definition
* Version 1:
- initial commit to add new feature (download models and activity lifecycle)
> [Android] update sample app

- native/example_filter_performance_profile/nnstreamer_example_filter_performance_profile.c
* changed tflite model link 
* type moel -> model
Signed-off-by: Hyunji Choi hjbc0921@gmail.com
> [TYPO] change in link to tflite model 

- android/example_app/nnstreamer-multi/AndroidManifest.xml
- android/example_app/nnstreamer-multi/res/xml/network_security_config.xml
- android/example_app/nnstreamer-ssd/AndroidManifest.xml
- android/example_app/nnstreamer-ssd/res/xml/network_security_config.xml
Fixed issue #39
This commit is to support http and https protocol for Android applications
such as nnstreamer-ssd and nnstreamer-multi. After this commit, these
application download neural network model files.
**Changelog**
- Added http protocol as well as https protocol
- Declared 'cleartextTrafficPermitted" with "true" by default
- Added network_security_config.xml
---
In general, github system automatically copies your commit message for your convenience.
Please remove unused part of the template after writing your own PR description with this template.
```bash
$ git commit -s filename1 filename2 ... [enter]
Summarize changes in around 50 characters or less
More detailed explanatory text, if necessary. Wrap it to about 72
characters …
```
> Android: Support http protocol as well as https

- android/example_app/nnstreamer-multi/res/layout/main.xml
- android/example_app/nnstreamer-multi/src/org/freedesktop/gstreamer/nnstreamer/NNStreamerActivity.java
Add Button to run automatically. If this button is eabled, it run
camera -> enable face -> enable hand -> enable pose -> disable pose ->
disable hand -> disable face -> enable face -> ... with 10 sec interval.
1. Build test:	 [X]Passed [ ]Failed [ ]Skipped
2. Run test:	 [X]Passed [ ]Failed [ ]Skipped
Signed-off-by: jijoong.moon <jijoong.moon@samsung.com>
> [Multi] Add Button to run automatically

- native/example_cam/nnstreamer_example_cam.c
- native/example_decoder_image_labelling/nnstreamer_example_decoder_image_labelling.c
- native/example_image_classification/nnstreamer_example_image_classification.c
- native/example_object_detection_tensorflow/nnstreamer_example_object_detection_tf.cc
- native/example_object_detection_tensorflow_lite/nnstreamer_example_object_detection_tflite.cc
- native/example_sink/nnstreamer_sink_example.c
- native/example_sink/nnstreamer_sink_example_play.c
- native/example_speech_command_tensorflow_lite/nnstreamer_example_speech_command_tflite.c
This commit prevents possible error when using
check_cond_error macro.
Signed-off-by: hjbc0921 <hjbc0921@gmail.com>
> Wrap macro with do{} while(0)

- native/example_decoder_image_labelling/nnstreamer_example_decoder_image_labelling.c
- native/example_filter_performance_profile/nnstreamer_example_filter_performance_profile.c
- native/example_image_classification/nnstreamer_example_image_classification.c
- native/example_image_classification/nnstreamer_example_image_classification.py
- native/example_object_detection_tensorflow/nnstreamer_example_object_detection_tf.cc
- native/example_object_detection_tensorflow_lite/nnstreamer_example_object_detection_tflite.cc
- native/example_speech_command_tensorflow_lite/nnstreamer_example_speech_command_tflite.c
This commit updates model paths and comments
in native examples according to PR #44.
Signed-off-by: hjbc0921 <hjbc0921@gmail.com>
> Update model paths in native examples

- meson.build
- native/example_image_classification_caffe2/meson.build
- native/example_image_classification_caffe2/nnstreamer_example_image_classification_caffe2.c
- native/meson.build
this example is implemented based on Caffe2
> [Native/Caffe2] upload the image classification example

- meson.build
> [Meson] change the build dependency @open sesame 7/11 14:24

- native/example_image_classification_caffe2/nnstreamer_example_image_classification_caffe2.c
add a missed semi-colon at the code
> [Native/Caffe2] fix a bug

- packaging/nnstreamer-example.spec
disable tensorflow in .spec (currently not supported)
> [Build] block tensorflow

- Tizen.native/Application/fetch_shared_object.sh
- Tizen.native/Application/src/main.c
update changed api function and definition
> [Tizen/Native] sync up api changes

- bash_script/example_models/get-model-image-classification-tflite.sh
- bash_script/example_models/get-model-object-detection-tf.sh
- bash_script/example_models/get-model-object-detection-tflite.sh
- bash_script/example_models/get-model-speech-command.sh
- bash_script/example_models/get-model.sh
- bash_script/example_models/meson.build
Delete the existing get-model scripts and merge it into get-model.sh
Identify models by arguments
related issue: #64 
> [CodeClean] merge get-model scripts

- native/example_decoder_image_labelling/nnstreamer_example_decoder_image_labelling.c
remove a content about load labels in function brief.
related issue: #72 
> [CodeClean] correct the brief

- Tizen.native/README.md
- android/README.md
This patch fixes typo in README.md
Signed-off-by: Injae Kang <abcinje@gmail.com>
> [Typo] Fix typo

- .gitignore
I added .gitignore file to ignore build directory.
This patch resolves #74
Signed-off-by: Injae Kang <abcinje@gmail.com>
> Create .gitignore to ignore build directory

- native/example_decoder_image_labelling/nnstreamer_example_decoder_image_labelling.c
- native/example_filter_performance_profile/nnstreamer_example_filter_performance_profile.c
- native/example_image_classification_tflite/nnstreamer_example_image_classification_tflite.c
- native/example_image_classification_tflite/nnstreamer_example_image_classification_tflite.py
- native/example_object_detection_tensorflow/nnstreamer_example_object_detection_tf.cc
- native/example_object_detection_tensorflow_lite/nnstreamer_example_object_detection_tflite.cc
- native/example_speech_command_tensorflow_lite/nnstreamer_example_speech_command_tflite.c
- native/example_two_tensor_stream/nnstreamer_example_two_tensor_stream.c
change invalid get model guidances in native example sources.
related issue: #77 
> [guide] update the get model guidances

- bash_script/example_models/get-model.sh
- native/example_image_classification_caffe2/nnstreamer_example_image_classification_caffe2.c
insert contents get image-classification-caffe2 model and labels.txt
confirmed it worked well in example_image_classification_caffe2
related issue: #65 
Signed-off-by: Dongwon Lee <dongwon1103@naver.com>
> [Model] Add getting caffe2 mobilenet_v2 script

- meson.build
- templates/tensor_filter_subplugin/meson.build
> [Meson] update version

- Tizen.native/ImageClassification/tizen-manifest.xml
add `machine_learning`, `machine_learning.inference` features at the native sample app
> [Tizen/Native] add the features at the manifest file

- Tizen.native/SingleSample/src/nnstreamer-sample-single.c
- bash_script/example_image_segmentation_tensorflow_lite/gst-launch-image-segmentation-tflite.sh
- bash_script/example_object_detection_tensorflow/gst-launch-object-detection-tf.sh
- bash_script/example_object_detection_tensorflow_lite/gst-launch-object-detection-tflite.sh
- native/example_image_classification_caffe2/nnstreamer_example_image_classification_caffe2.c
- native/example_image_classification_tflite/nnstreamer_example_image_classification_tflite.c
- native/example_object_detection_tensorflow/nnstreamer_example_object_detection_tf.cc
- native/example_object_detection_tensorflow_lite/nnstreamer_example_object_detection_tflite.cc
- native/example_speech_command_tensorflow_lite/nnscustom_speech_command_tflite.c
- native/example_speech_command_tensorflow_lite/nnstreamer_example_speech_command_tflite.c
- native/example_two_tensor_stream/nnstreamer_example_two_tensor_stream.c
1. set exact tensor dimension in the pipeline
2. fix indent and add simple model info comment
> [Example] dimension in pipeline

- bash_script/example_models/get-model.sh
- native/example_text_classification/meson.build
- native/example_text_classification/nnstreamer_example_text_classification_tflite.c
- native/meson.build
Text classification example with Tensorflow-Lite.
When the user types a movie review,  pretrained model predicts if a paragraph's sentiment is positive or negative. 
TF-lite model can be downloaded here : https://www.tensorflow.org/lite/models/text_classification/overview
1. Build test: [ * ]Passed [ ]Failed []Skipped
2. Run test: [ * ]Passed [ ]Failed []Skipped
> [Example] Text classification with Tensorflow-Lite

- android/example_app/api-sample/src/main/java/org/nnsuite/nnstreamer/sample/MainActivity.java
Android API changed, TensorsData has metadata and data callback has updated.
> [Android/Api] update sample code

- android/example_app/capi-sample/build.gradle
- android/example_app/capi-sample/src/main/AndroidManifest.xml
- android/example_app/capi-sample/src/main/java/org/nnsuite/nnstreamer/sample/MainActivity.java
- android/example_app/capi-sample/src/main/jni/nnstreamer-native-sample.c
Update sample code to execute SNAP model.
(native API with pipeline description)
> [Android/SNAP] sample code for SNAP

- Tizen.platform/Vivante_pipeline_NonGUI_inceptionV3/src/main.c
- Tizen.platform/Vivante_single_NonGUI_inceptionV3/src/main.c
set classes and print data_size to check it
> [Tizen.platform] fix iteration bug

- Tizen.platform/Vivante_pipeline_NonGUI_inceptionV3/README.md
- Tizen.platform/Vivante_pipeline_NonGUI_inceptionV3/src/main.c
- Tizen.platform/Vivante_single_NonGUI_inceptionV3/README.md
- Tizen.platform/Vivante_single_NonGUI_inceptionV3/src/main.c
Rather than the fixed paths, set file path through arguments
> [Tizen.platform] make file names available to be changed

- bash_script/example_models/get-model.sh
- native/example_pose_estimation_tflite/README.md
- native/example_pose_estimation_tflite/meson.build
- native/example_pose_estimation_tflite/nnstreamer_example_pose_estimation_tflite.cc
- native/meson.build
Single person pose estimation with public TFLlite model.
It draws 17 body points of a person in input video stream. Details about the model can be found here:
https://www.tensorflow.org/lite/models/pose_estimation/overview
> [Ubuntu-Native/Example] Pose estimation example with TFLite model

- Tizen.native/ImageClassification/inc/main.h
- Tizen.native/ImageClassification/src/main.c
getting app privilege at app create time.
> [Tizen.native] change the order of getting privilege

- Tizen.platform/Vivante_pipeline_NonGUI_inceptionV3/packaging/vivante-inceptionv3-pipeline.spec
> [Tizen.platform] fix typo which occurs gbs build FAILURE at resource path

- android/example_app/capi-sample/src/main/java/org/nnsuite/nnstreamer/sample/MainActivity.java
- android/example_app/capi-sample/src/main/jni/nnstreamer-native-sample.c
Update android sample code for API changes.
> [Android] update sample for API changes

- Tizen.native/ObjectDetection/README.md
- Tizen.native/ObjectDetection/inc/data.h
- Tizen.native/ObjectDetection/src/data.c
- Tizen.native/ObjectDetection/src/main.c
- Tizen.native/ObjectDetection/tizen-manifest.xml
- Modifying PR #111 to run on Tizen Device (TM1).
- Feature of overlaying bounding boxes to original image feature is not yet implemented.
- Add a demo .gif file
> [Tizen.native] Object detection (bounding boxes) example

- android/example_app/api-sample/build.gradle
- android/example_app/api-sample/libs/Readme.txt
- android/example_app/api-sample/src/main/java/org/nnsuite/nnstreamer/sample/MainActivity.java
Update API example to run NNFW model (add.tflite)
> [Android/API] example to run NNFW

- android/example_app/capi-sample/build.gradle
- android/example_app/capi-sample/src/main/java/org/nnsuite/nnstreamer/sample/MainActivity.java
- android/example_app/capi-sample/src/main/jni/nnstreamer-native-sample.c
Update native example, including nnfw sample code.
Also add SNAP-tensorflow and remove jave code to initialize nnstreamer.
> [Android] update native example to run NNFW

- README.md
- debian/changelog
- debian/control
Provides a simple guide for example execution on the main page.
> [README] Add quick start guide

- Tizen.platform/Vivante_pipeline_NonGUI_inceptionV3/packaging/vivante-inceptionv3-pipeline.spec
- Tizen.platform/Vivante_single_NonGUI_inceptionV3/packaging/vivante-inceptionv3-single.spec
change the licenses of examples to LGPL-2.1
> [Tizen/Platform] change license to LGPL-2.1

- Tizen.platform/Vivante_pipeline_experiments/src/main.c
change the running time to an argument to adjust it
> [Tizen/platform] running time adjustment

- README.md
- android/README.md
- android/example_app/README.md
Fixed issue https://github.com/nnstreamer/nnstreamer/issues/2349.
This commit is to update the existing document in order to re-upload
the nnstreamer multi-model application because the application management
of Google Store is changed.
---
> [Android] Updated manual for nnstreamer multi-model app

- native/example_repo_custom_easy/example_repo_custom_easy.cc
- native/example_repo_custom_easy/meson.build
The filters will work one by one. and additional logic for EOS has been added
> [Native] update the sample application - @open sesame 06/22 19:24

- native/example_repo_custom_easy/example_repo_custom_easy.cc
make output log clear and remove silent & async option
> [Native/Repo] code clean

- native/example_tensor_mux/example_tensor_mux.cc
- native/example_tensor_mux/meson.build
- native/meson.build
this example can be activated after upgrading the new `sync_mode: refresh` of `tensor_mux`. The new mode will be applied soon at [nnstreamer](https://github.com/nnstreamer/nnstreamer) repo.
> [Wait for the new PR][Native] upload the example related with tensor_mux

- android/example_app/api-sample/src/main/java/org/nnsuite/nnstreamer/sample/MainActivity.java
- android/example_app/capi-sample/src/main/jni/Application.mk
- android/example_app/capi-sample/src/main/jni/nnstreamer-native-sample.c
update android java/c api changes.
- api changes about custom-easy filter
- check nnfw availability before starting the pipeline
> [Android] update api changes

- android/example_app/nnstreamer-media-ssd/jni/Android-nnstreamer.mk
- android/example_app/nnstreamer-multi/jni/Android-nnstreamer.mk
- android/example_app/nnstreamer-ssd/jni/Android-nnstreamer.mk
Update mk file to build nnstreamer. Set predefined list and sync to api build.
> [Android] mk file to build nnstreamer

- Tizen.platform/Tizen_IoT_text_classification_NonGUI/src/nnstreamer_tizen_iot_text_classification.c
Fix build and runtime error.
1. missing semicolon
2. A new line was added due to CI, and a problem occurred while parsing voca.
> [Tizen/platform] Fix build and runtime error

- native/example_image_classification_tflite/nnstreamer_example_image_classification_tflite.py
[native] Modify python shebang
1. Build test: [*]Passed [ ]Failed []Skipped
2. Run test: [*]Passed [ ]Failed []Skipped
> [native] Modify python shebang

- native/example_sink/meson.build
- native/example_sink/nnstreamer_sink_example.py
Usage:
$ python nnstreamer_sink_example.py video
$ python nnstreamer_sink_example.py audio
$ python nnstreamer_sink_example.py text
----
This patch partially resolves: https://github.com/nnstreamer/nnstreamer-example/issues/155
> [native] port nnstreamer_sink_example to Python

- bash_script/example_models/get-model.sh
Openvino is available in Ubuntu and Tizen now, the script is modified to download the model
> [OPENVINO] Modify the get model script to download openvino model

- native/example_sink/meson.build
- native/example_sink/nnstreamer_sink_example_play.py
Usage:
$ python nnstreamer_sink_example_play.py
Resolves: #155 
1. Build test: [ * ]Passed [ ]Failed [ ]Skipped
2. Run test: [ * ]Passed [ ]Failed [ ]Skipped
> [native] port nnstreamer_sink_example_play to Python

- templates/tensor_filter_subplugin/deploy.sh
- templates/tensor_filter_subplugin/meson.build
- templates/tensor_filter_subplugin/packaging/tensor-filter-TEMPLATE.spec.in
- templates/tensor_filter_subplugin/src/tensor_filter_subplugin.c
NNStreamer tensor-filter properties are recently changed and updated.
Fix errors and apply the changes to sub-plgin template.
> [Template] update nnstreamer changes

- android/example_app/api-sample/src/main/java/org/nnsuite/nnstreamer/sample/MainActivity.java
- Add pipeline example and single example with SNPE
> [Android] Add Java api example with SNPE

- native/example_face_detection_tflite/README.md
Add README.md to initialize project directory
Signed-off-by: YongjoonSeo <koreakkrea12@naver.com>
> [native] Add readme into example_face_detection_tflite

- native/example_face_detection_tbd/README.md
- native/example_face_detection_tflite/README.md
Add directory for face_detection_tflite app. The Source code and details will be updated later
Signed-off-by: dreamfinder2019 jangjongha.sw@gmail.com
> [native] Add directory for face_detection_tflite app

- native/example_face_detection_tflite/README.md
modify readme.md in example face detection file to test PR
Signed-off-by: yeseul4072 <yeseul4072@gmail.com>
> [native] Modify README.md in example_face_detection_tflite

- native/example_face_detection_tflite/nnstreamer_example_face_detection_tflite.py
- native/example_object_detection_tensorflow_lite/nnstreamer_example_object_detection_tflite.py
We are currently working on porting object_detection_tflite to python. At this moment, We have succeeded in reading data from the label files. More elements like bus control and registering callbacks will be implemented shortly.
> [native] Upload base code of face_detection_tflite and python port of object_detection_tflite

- bash_script/example_models/get-model.sh
- native/example_face_detection_tflite/README.md
- native/example_face_detection_tflite/meson.build
- native/example_face_detection_tflite/nnstreamer_example_face_detection_tflite.py
- native/example_object_detection_tensorflow_lite/meson.build
- native/example_object_detection_tensorflow_lite/nnstreamer_example_object_detection_tflite.py
- native/meson.build
Python version of object detection and face detection using Tflite and nnstreamer
now works full functonional. Both code detects objects or face.
PyCairo was used as visualization tool.
For face detection, the code shows only the largest detected face in the video,
while the other faces are covered with black rectangles.
Right now, These two codes have not yet implemented mutex or thread-related functions.
> [native] Update full functional object and face detection tflite.py

- android/example_app/nnstreamer-ssd-autocapture/README.md
Add README.md for nnstreamer-ssd-autocapture for pr-test
Signed-off-by: sang.hyun.park <park03851@naver.com>
> [Android] Add README.md for nnstreamer-ssd-autocapture

- native/example_multi_model_tflite/README.md
- native/example_multi_model_tflite/meson.build
- native/example_multi_model_tflite/nnstreamer_example_multi_model_tflite.py
- native/meson.build
nnstreamer_example_multi_model_tflite.py detects face and objects.
In order to implement multi-model in a single application, we made use of two 'tee's.
We expect that this application can be used in future development for several purposes
like pixelating faces or hazardous objects
> [native] Add example_multi_model_tflite, which detects face and objects.

- native/example_face_detection_tflite/README.md
- native/example_multi_model_tflite/README.md
Add README.md files for new python examples, which are the followings
- nnstreamer_example_face_detection_tflite.py
- nnstreamer_example_multi_model_tflite.py
README files consist of brief introduction of each example, and explain how to run.
> [native] Add READMEs for new python examples

- native/example_pose_estimation_tflite/nnstreamer_example_pose_estimation_tflite.py
Add nnstreamer_example_pose_estimation_tflite.py based on c++ example file.
Signed-off-by: soo-ni <ksb940925@gmail.com>
> [native] Add pose estimation python example

- native/example_multi_model_tflite/meson.build
- native/example_multi_model_tflite/nnstreamer_example_multi_model_face_pose.py
This application features face detecting and eye mask using face model and pose estimate model.
It is one of the example of implementing multimodel application using nnstreamer.
This application only supports one person right now due to having array index issues
while applying multiple pose estimating through filters.
Applying valve for tees and thread feature will be added in future.
--UPDATE 2020-10-03 PM 23:03 KST--
I updated this code to work properly with two persons. There was a pipeline issue in previous code. I rebuilt the entire pipeline, and serious issues were found and fixed.
> [native] Add Multimodel Application using Face and Pose model

- native/example_multi_model_tflite/README.md
- native/example_multi_model_tflite/nnstreamer_example_multi_model_face_pose.py
We made a updates for multi-model examples to address face angle issue.
And we added README.md contents for mult-imodel examples.
Additionally, We made a test for multiple faces in face_pose.py, up to three faces can be masked.
More updates, descriptions and contents will be updated in future.
> [native] Add README.md contents and update multi-model example

- Tizen.native/PipelineSample/inc/nnstreamer-sample-pipeline.h
- Tizen.native/PipelineSample/src/nnstreamer-sample-pipeline.c
- Tizen.native/SingleSample/inc/nnstreamer-sample-single.h
- Tizen.native/SingleSample/src/nnstreamer-sample-single.c
- Tizen.platform/Tizen_IoT_ImageClassification/meson.build
- Tizen.platform/Tizen_IoT_text_classification_NonGUI/meson.build
- meson.build
- native/example_speech_command_tensorflow_lite/nnscustom_speech_command_tflite.c
change license in meson script and source file (LGPL-2.1)
> [Meson] update license arg

- native/example_rtmp_live_streaming/README.md
- native/example_rtmp_live_streaming/ezstreamer.py
- native/example_rtmp_live_streaming/ezstreamer.ui
- native/example_rtmp_live_streaming/meson.build
- native/example_rtmp_live_streaming/nnstreamer_example_face_detection_rtmp.py
- native/meson.build
rtmp_example and pyqt5 based gui application has added to native/example_rtmp_live_streaming
This gui application is still in early stage, so some optimization and debugging may required.
The name of gui application will be ezstreamer.
Additional packages like Pyqt5 and Pyslide is required.
> [native] Add example_rtmp_live_streaming example

- native/example_rtmp_live_streaming/ezstreamer.py
The following additions and changes have been updated in EZStreamer.
1) Now EZStreamer can change overlay mode in real time.
However, in the case of changing the streaming mode, since the rtmp key is needed,
quit the streaming is required.
2) Increased the video frames for tensor_filter to 15fps.
3) Changed the pipeline for all filter elements to run at once.
4) A function to exclude masking for large faces detected within the screen has been added.
5) Minimized the number of print warning and error logs that can be occured by buffer drop and streaming.
6) As the above update is reflected, we've made some changes to the streaming controller UI function.
> [native] Apply ui changes, add new features, adjust pipelines for ezstreamer

- android/example_app/nnstreamer-ssd-autocapture/jni/nnstreamer-ex.cpp
- android/example_app/nnstreamer-ssd-autocapture/jni/nnstreamer-jni.c
- android/example_app/nnstreamer-ssd-autocapture/jni/nnstreamer-jni.h
[Edit] nnstreamer-jni.h : Add data structure to contain conditions for autocapture.
[Edit] nnstreamer-jni.c : Add 'NativeDeleteLineAndLabel', 'NativeInsertLineAndLabel', 'NativeGetCondition', 'NativeGetAutoCapture' functions based on jni.
[Edit] nnstreamer-ex.cpp : Implement 'NativeDeleteLineAndLabel', 'NativeInsertLineAndLabel', 'NativeGetCondition', 'NativeGetAutoCapture' functions.
When objects that meet the conditions are visible on the screen, can take picture automatically.
When in autocapture mode, can erase the label's name and line so that only objects can appear in the picture taken.
Signed-off-by: sang.hyun.park <park03851@naver.com>
> [Android] Add functions of autocapture to run in android Activities

- android/example_app/nnstreamer-ssd-autocapture/res/layout/activity_selected_image.xml
- android/example_app/nnstreamer-ssd-autocapture/res/layout/activity_setting.xml
- android/example_app/nnstreamer-ssd-autocapture/res/layout/main.xml
- android/example_app/nnstreamer-ssd-autocapture/res/values/objects.xml
[Edit] main : Add toggle button.
[Edit] activity_preview : edit newline.
[Edit] activity_setting : edit newline.
[Add] activity_selected_image : Show 'SelectedImageActivity.java'.
[Edit] object : Add a few objects.
Signed-off-by: sang.hyun.park <park03851@naver.com>
> [Android] Edit all xml and add new xml

- android/example_app/nnstreamer-ssd-autocapture/src/org/freedesktop/gstreamer/nnstreamer/Conditions.java
- android/example_app/nnstreamer-ssd-autocapture/src/org/freedesktop/gstreamer/nnstreamer/NNStreamerActivity.java
- android/example_app/nnstreamer-ssd-autocapture/src/org/freedesktop/gstreamer/nnstreamer/PreviewActivity.java
- android/example_app/nnstreamer-ssd-autocapture/src/org/freedesktop/gstreamer/nnstreamer/SelectedImageActivity.java
- android/example_app/nnstreamer-ssd-autocapture/src/org/freedesktop/gstreamer/nnstreamer/SettingActivity.java
[Edit] NNStreamerActivity :
1. Add automatic and manual capture modes.
2. Add function to count down for 3 seconds after clicking the button in Auto Capture mode and recognizing objects that meet the conditions.
3.Add a native function to be used in jni.
[Add] Conditions : Object created to hand over set conditions to jni.
[Add] SelectedImageActivity : Add function that bring in and show selected pictures from the gallery.
[Edit] PreviewActivity : Remove 'import' that is not needed.
[Edit] SettingActivity : Remove 'import' that is not needed.
Signed-off-by: sang.hyun.park <park03851@naver.com>
> [Android] Edit all Activities and add new Activities

- android/example_app/api-sample/src/main/java/org/nnsuite/nnstreamer/sample/MainActivity.java
Fix bug, invalid index to print tensor info in API sample.
> [Android] invalid index

- android/example_app/use-camera-with-nnstreamer-java-api/src/main/AndroidManifest.xml
- android/example_app/use-camera-with-nnstreamer-java-api/src/main/java/org/nnsuite/nnstreamer/sample/MainActivity.java
- android/example_app/use-camera-with-nnstreamer-java-api/src/main/res/layout/activity_main.xml
Using new method with glimagesink element, an application can set a surface in the pipeline.
> [Android] example to set surface

- README.md
- Add a table showing ubuntu native examples
- Add a table showing bash script examples
- Add a table showing Tizen applications
- Add a table showing Android applications
Preview: https://github.com/anyj0527/nnstreamer-example/blob/add-example-table/README.md#example-list
> [doc] Add List of examples

- README.md
> [doc] Add object detection example using 2 cameras

- native/example_early_exit/example_early_exit.c
- native/example_early_exit/example_early_exit_capi.c
Modify the samples because the property names of the tensor filter have been changed.
outputCombination -> output-combination
> [Filter/option] Fix tensor filter combination options

- meson.build
- packaging/nnstreamer-example.spec
The pkg name for ml-inference api will be changed.
> [Build] change pkg name for ml c-api

- native/example_repo_custom_easy/example_repo_custom_easy.cc
- native/example_tensor_mux/example_tensor_mux.cc
change property name of tensor-mux sync mode.
> [Mux] change property name

- Tizen.native/ObjectDetection/src/main.c
- bash_script/example_object_detection_tensorflow/gst-launch-object-detection-tf.sh
- bash_script/example_object_detection_tensorflow_lite/gst-launch-object-detection-tflite.sh
- bash_script/example_tensorif/gst-launch-tensorif-passthrough.sh
- bash_script/example_tensorif/gst-launch-tensorif-tensorpick.sh
This change is related to https://github.com/nnstreamer/nnstreamer/pull/3195/files.
See also: https://github.com/nnstreamer/nnstreamer/pull/3195
2. Run test: [ ]Passed [ ]Failed [*]Skipped
> [Wait for nnstreamer/#3195][Decoder/BoundingBox] change the name of an option

- bash_script/example_early_exit/README.md
- bash_script/example_join/README.md
- native/example_early_exit/README.md
> Adding information for join plugin

- Tizen.native/ImageClassification_SingleShot/inc/view.h
- Tizen.native/ImageClassification_SingleShot/src/view.c
by adding proper cb, fix the bug app is not closed.
2. Run test: [*Passed [ ]Failed [ ]Skipped
> [Tizen/Native] fix the bug not closing app

- native/example_query_object_detection/example_query_object_detection.c
- native/example_query_object_detection/meson.build
- native/meson.build
Add query query sample app using ML-API
BUG: Query server does not run using excutable file while the same pipeline works well with gst-launch.
```
This works well..
server
gst-launch-1.0 tensor_query_serversrc host=127.0.0.1 port=3001 ! tensor_filter framework=tensorflow-lite model=./tflite_model/ssd_mobilenet_v2_coco.tflite ! tensor_decoder mode=bounding_boxes option1=mobilenet-ssd option2=./tflite_model/coco_labels_list.txt option3=./tflite_model/box_priors.txt option4=640:480 option5=300:300 ! tensor_converter ! other/tensors,num_tensors=1,dimensions=4:640:480:1,types=uint8 ! tensor_query_serversink host=127.0.0.1 port=3000 sync=false async=false
client
./nnstreamer_example_query_object_detection client
```
```
This isn't working..
server
./nnstreamer_example_query_object_detection …
```
> [QUERY] Add query sample app using ML-API

- native/example_query_object_detection/example_query_object_detection.c
During sleep, query server cannot hanlde event.
Remove sleep and use g_main_loop.
> [native] Remove sleep time from query app

- native/example_query_object_detection/README.md
add README.md for tensor query native app
> [native] add README.md for tensor query native app

- native/example_object_detection_tensorflow/nnstreamer_example_object_detection_tf.cc
- native/example_object_detection_tensorflow_lite/nnstreamer_example_object_detection_tflite.cc
Use tensor decoder to draw bounding box.
> [native/objectDetection] Use tensor decoder for bounding box

- bash_script/example_mqtt_object_detection_tflite/gst-launch-mqtt-object-detection-tflite-pub.sh
- bash_script/example_mqtt_object_detection_tflite/gst-launch-mqtt-object-detection-tflite-sub.sh
- bash_script/example_mqtt_object_detection_tflite/meson.build
- bash_script/meson.build
Add MQTT object detection app.
- Pub: Send video raw
- Sub: Object detection
1. Build test: [ *]Passed [ ]Failed []Skipped
> [bash] Add mqtt object detection app.

- bash_script/example_tensor_query/gst-launch-tensor_query_client.sh
- bash_script/example_tensor_query/gst-launch-tensor_query_server.sh
Send raw video stream to server instead of tensor stream.
> [query/ObjectDetection] Send raw video to server

- meson.build
- native/edgeAI_performance_benchmark/meson.build
- native/edgeAI_performance_benchmark/profiling.sh
- native/edgeAI_performance_benchmark/profiling_rpi.sh
- native/edgeAI_performance_benchmark/pubsub_performance_benchmark.c
- native/edgeAI_performance_benchmark/tensor_query_performance_benchmark.c
- native/example_early_exit/meson.build
- native/example_query_object_detection/meson.build
- native/meson.build
EdgeAI performance benchmark app using image classification (tflite).
Query (TCP, MQTT-hybrid), Pyb/Sub (ZMQ, MQTT)
> [edgeAI] Performance benchmark app.

- bash_script/example_tensor_query/gst-launch-tensor_query_client.sh
- bash_script/example_tensor_query/gst-launch-tensor_query_server.sh
This patch removes unnecessary backslash
Signed-off-by: yelini-jeong <yelini.jeong@samsung.com>
> [query] remove unnecessary backslash

- android/example_app/README.md
- android/example_app/nnstreamer-media-ssd/src/org/freedesktop/gstreamer/nnstreamer/DownloadModel.java
- android/example_app/nnstreamer-multi/src/org/freedesktop/gstreamer/nnstreamer/DownloadModel.java
- android/example_app/nnstreamer-ssd-autocapture/README.md
- android/example_app/nnstreamer-ssd-autocapture/src/org/freedesktop/gstreamer/nnstreamer/DownloadModel.java
- android/example_app/nnstreamer-ssd/src/org/freedesktop/gstreamer/nnstreamer/DownloadModel.java
- android/multi_device_shared_lib/src/org/freedesktop/nnstreamer/nnstreamermultidevice/DownloadModel.java
- bash_script/example_models/get-model.sh
Uodate NN model download url to http://nnstreamer.mooo.com/warehouse/nnmodels/
> Update NN mlodel download url.

- bash_script/example_models/get-model.sh
- native/example_object_detection_tensorflow_lite/nnstreamer_example_object_detection_tflite.py
- native/example_pose_estimation_tflite/meson.build
- native/example_pose_estimation_tflite/nnstreamer_example_pose_estimation_tflite.cc
- native/example_pose_estimation_tflite/nnstreamer_example_pose_estimation_tflite.py
Use tensor decoder for bounding box and pose estimation result
>  Use tensor decoder for bounding box and pose estimation result

- meson.build
- native/example_low_light_image_enhancement/README.md
- native/example_low_light_image_enhancement/meson.build
- native/example_low_light_image_enhancement/nnstreamer_example_low_light_image_enhancement.cc
Low light image enhancement with Tenworflow-Lite model.
This example has a dependency on opencv4.
Signed-off-by: yelini-jeong <yelini.jeong@samsung.com>
> [Example] Low light image enhancement cc example with TF-lite

- android/example_app/README.md
- android/example_app/nnstreamer-media-ssd/src/org/freedesktop/gstreamer/nnstreamer/DownloadModel.java
- android/example_app/nnstreamer-multi/src/org/freedesktop/gstreamer/nnstreamer/DownloadModel.java
- android/example_app/nnstreamer-ssd-autocapture/README.md
- android/example_app/nnstreamer-ssd-autocapture/src/org/freedesktop/gstreamer/nnstreamer/DownloadModel.java
- android/example_app/nnstreamer-ssd/src/org/freedesktop/gstreamer/nnstreamer/DownloadModel.java
- android/multi_device_shared_lib/src/org/freedesktop/nnstreamer/nnstreamermultidevice/DownloadModel.java
- bash_script/example_models/get-model.sh
Change CI server domain name from nnstreamer.mooo.com to ci.nnstreamer.ai
> [Doc] Change CI server domain name

- bash_script/example_tensor_query_mqtt/README.md
- bash_script/example_tensor_query_mqtt/gst-launch-tensor_query_mqtt_client.sh
- bash_script/example_tensor_query_mqtt/gst-launch-tensor_query_mqtt_server_1.sh
- bash_script/example_tensor_query_mqtt/gst-launch-tensor_query_mqtt_server_2.sh
Update query mqtt-hybrid bash app.
> [Query] Update query mqtt-hybird applicaiton.

- packaging/nnstreamer-example.spec
The macro name should be composed of alphanumeric characters and '_'.
> [Spec] update macro name

- bash_script/example_tensor_query_mqtt/gst-launch-tensor_query_mqtt_client.sh
- bash_script/example_tensor_query_mqtt/gst-launch-tensor_query_mqtt_server_1.sh
- bash_script/example_tensor_query_mqtt/gst-launch-tensor_query_mqtt_server_2.sh
- Fix invalid argument number
- Add host property to client
> [Bash/query] Update mqtt-hybrid bash script

- bash_script/meson.build
- debian/control
- meson.build
- native/edgeAI_performance_benchmark/meson.build
- native/edgeAI_performance_benchmark/profiling.sh
- native/edgeAI_performance_benchmark/profiling_rpi.sh
- native/edgeAI_performance_benchmark/pubsub_performance_benchmark.c
- native/edgeAI_performance_benchmark/tensor_query_performance_benchmark.c
- native/meson.build
- packaging/nnstreamer-example.spec
- Update properies of the query elements
- Add edgesrc / edgesink
1. Build test: [* ]Passed [ ]Failed [ ]Skipped
2. Run test: [* ]Passed [ ]Failed [ ]Skipped
> [Edge] update nnstreamer-edge performance benchmark app

- bash_script/example_audio_classification/gst-launch-audio-classification.sh
- bash_script/example_audio_classification/meson.build
- bash_script/meson.build
- Add a simple bash script example for audio classification using yamnet tflite model
REF: https://tfhub.dev/google/lite-model/yamnet/tflite/1
> [bash] Add a simple audio classification example

- bash_script/example_yolov5/README.md
- bash_script/example_yolov5/coco.txt
- bash_script/example_yolov5/gst-launch-object-detection-yolov5-tflite.sh
- bash_script/example_yolov5/gst-launch-object-detection-yolov5-torchscript.sh
- bash_script/example_yolov5/meson.build
- bash_script/meson.build
- meson.build
- Add simple bash script example with yolov5 models
> [bash] Add yolov5 object detection example

- bash_script/example_yolov5/README.md
- bash_script/example_yolov5/gst-launch-object-detection-yolov5-tflite.sh
- Add a simple pipeline with quantized tflite model using GPU delegate
> [bash] Add yolov5 bash script example with quantized tflite model @open sesame 1/3 17:43

- Tizen.platform/Tizen_IoT_inference_offloading/gen_tizen_iot_inference_offloading_rpm.sh
- Tizen.platform/Tizen_IoT_inference_offloading/meson.build
- Tizen.platform/Tizen_IoT_inference_offloading/nnstreamer_example_inference_offloading_edge.c
- Tizen.platform/Tizen_IoT_inference_offloading/nnstreamer_example_inference_offloading_leaf_pipe.c
- Tizen.platform/Tizen_IoT_inference_offloading/nnstreamer_example_inference_offloading_leaf_rt.c
- Tizen.platform/Tizen_IoT_inference_offloading/packaging/tizen-iot-inference-offloading.manifest
- Tizen.platform/Tizen_IoT_inference_offloading/packaging/tizen-iot-inference-offloading.spec
Application that transmits data from leaf device that uses only nns_edge to edge server that uses nnstreamer query pipeline.
> [Edge] leaf device to query pipeline app

- Tizen.platform/Tizen_IoT_inference_offloading/nnstreamer_example_inference_offloading_edge.c
Use tensor-dim API instead of hardcoded dimension.
> Change custom easy info

- Tizen.platform/ml_remote_service_registration/gen_ml_remote_service_rpm.sh
- Tizen.platform/ml_remote_service_registration/meson.build
- Tizen.platform/ml_remote_service_registration/nnstreamer_example_ml_remote_service.c
- Tizen.platform/ml_remote_service_registration/packaging/ml_remote_service_registration.manifest
- Tizen.platform/ml_remote_service_registration/packaging/ml_remote_service_registration.spec
Add remote registration sample app to register pipeline description.
@todo remove separated spec file later
> [ML-service] Add remote registration sample app.

- bash_script/example_audio_classification/gst-launch-audio-classification.sh
- Handle recent NNStreamer's update on rank. (Use transpose rather than dimchg)
1. Build test: [ ]Passed [ ]Failed [*] Skipped
> [bash] Fix audio classification example script

- Tizen.native/MNIST_inference_after_training_offloading/receiver/src/receiver.c
- Tizen.native/MNIST_inference_after_training_offloading/sender/src/sender.c
- Enable setting model save path
- Modify input arguments of ml_service_remote_create
- Modify pipelines
> [Example] Enable setting the model save path

- Tizen.native/ImageClassification_SingleShot/src/main.c
- Tizen.native/ImageClassification_SingleShot/src/view.c
- Tizen.platform/Tizen_IoT_ImageClassification/packaging/tizen-iot-image-classification.spec
- Tizen.platform/Tizen_IoT_inference_offloading/packaging/tizen-iot-inference-offloading.spec
- Tizen.platform/Tizen_IoT_text_classification_NonGUI/packaging/tizen-iot-text-classification.spec
- Tizen.platform/Vivante_pipeline_NonGUI_inceptionV3/packaging/vivante-inceptionv3-pipeline.spec
- Tizen.platform/Vivante_pipeline_NonGUI_yoloV3/packaging/vivante-yolov3-pipeline.spec
- Tizen.platform/Vivante_pipeline_experiments/packaging/vivante-pipeline-experiment.spec
- Tizen.platform/Vivante_single_NonGUI_inceptionV3/packaging/vivante-inceptionv3-single.spec
- Tizen.platform/ml_remote_service_registration/packaging/ml_remote_service_registration.spec
- native/example_filter_performance_profile/nnstreamer_example_filter_performance_profile.c
- packaging/nnstreamer-example.spec
Update build pkg group in spec file.
> [Pkg] pkg group

- bash_script/example_image_style_transfer_onnx/README.md
- bash_script/example_image_style_transfer_onnx/gst-launch-image-style-transfer-onnx.sh
- bash_script/example_image_style_transfer_onnx/meson.build
- bash_script/example_models/get-model.sh
- bash_script/meson.build
- meson.build
- native/example_image_style_transfer_onnx/README.md
- native/example_image_style_transfer_onnx/meson.build
- native/example_image_style_transfer_onnx/nnstreamer_example_image_style_transfer_onnx.cc
- native/meson.build
- image style transfer example with onnx models
- add meson build
> [Example] upload image style transfer example with onnx models.

- android/example_app/README.md
This patch fixes broken link about how to build android
> [Android] fix broken link

- Tizen.native/yolo_model_training/src/yolo_model_training.c
- Tizen.platform/Vivante_pipeline_experiments/src/main.c
- native/example_data_preprocessing_for_training/nnstreamer_example_data_preprocessing.c
Code clean, fix mem leak case when using gstring util.
> [Build] fix mem leak

- Tizen.native/ml-svc-model/README.md
- Tizen.native/ml-svc-model/mobilenetv3-rpk/res/global/tizen.ai.model/model_description.json
- Tizen.native/ml-svc-model/mobilenetv3-rpk/res/global/tizen.ai.model/rpk_config.json
- Tizen.native/ml-svc-model/mobilenetv3-rpk/tizen-manifest.xml
- fix ml-svc-model/mobilenetv3-rpk
- the name and format of json file are modified. (model_description.json -> rpk_config.json)
- add metadata mlops key in tizen-manifest.xml
1. Build test: [*]Passed [ ]Failed []Skipped
2. Run test: [*]Passed [ ]Failed []Skipped
> [fix/ml-svc-model] fix the rpk example

- .github/workflows/tizen-web.yml
This patch adds github action workflow to build Tizen web application.
TODO
- Add native and .NET build script
- Build only when there are code modifications to the Tizen application
> [action] Add workflow to build Tizen web application 

- .github/workflows/tizen-web.yml
This patch adds steps to package and upload tizen web application in github action.
```
$ sdb install ImageClassificationOffloading.wgt
```
> [action] package Tizen web application and upload

- Tizen.native/whisper.cpp/README.md
- Add a README file to guide users to build/run the pipeline example.
- This example shows how to use `tensor_filter framework=cpp model=...`
> Add a README for whisper.cpp pipeline example

- Tizen.web/ImageClassificationOffloading/index.html
- Tizen.web/ImageClassificationOffloading/js/main.js
This patch removes hardcoded IP address and uses
tizen systeminfo to get IP address.
Reference : https://docs.tizen.org/application/web/api/8.0/device_api/mobile/tizen/systeminfo.html
> [Tizen/Web] Get IP address from device

- Tizen.native/ml-svc-model/imgcls/src/imgcls.c
- Let's use ml_information_* APIs.
> [svc] Change `ml_option_*` with `ml_information_*`

- Tizen.web/ImageClassificationOffloading/js/main.js
dimension ==> dimensions
type ==> types
CC: @niley7464
> Fix other/tensors property names

- Tizen.web/ImageClassificationOffloading/js/main.js
- Tizen.web/ImageClassificationOffloading/js/utils.js
- Tizen.web/ImageClassificationOffloadingService/inc/main.h
- Tizen.web/ImageClassificationOffloadingService/src/main.c
This patch adds logic to detect when offloading services disappear.
> [Tizen] Detect when offloading services disappear

- meson.build
Code clean, remove unnecessary cond when checking package dependency.
> [Meson] unnecessary cond

- .github/workflows/tizen-build.yml
This patch adds workflow_dispatch trigger option to build tizen application.
> [action] add workflow-dispatch to build tizen application

- Tizen.web/ImageClassificationOffloading/js/main.js
This patch changes service name due to android update.
> [Tizen] Change service name

- .github/workflows/tizen-build.yml
This patch fixes ultralytics version for stable build.
> [action] Ultralytics version fixed
