android/README.md

This commit is to provide how to compile the Gstreamer fulle source to
be compatible with ABI and API level of a specified Android version
(e.g., 7.0/Nougat).

doc: Added how to generate custom prebuild gst-android binary files

---

android/README.md

This commit is to append how to compile nnstreamer source code with ndk-build command
in order that developers can enable nnstreamer library on ther own Android device.

doc: Added how to build nnstreamer source code with ndk-build

---

android/README.md

This commit is to append how to build test application based on
NNstreamer library. It will be helpful to a developer that want to know
how to develop NNstreamer-based application on Android platform.
**Changes**
1. Updated the existing nnstreamer library build manual
2. Added how to build test applications

[Android] doc: Add how to build nnstreamer-based test app

---

android/README.md

This commit is to append helpful websites in order that the developers
can make their own custom platform using NNstreamer on the Android devices.

Android: Added reference websites

---

android/README.md

We sometimes meet a situation that have to manipulate the existing ELF binary files on the target device
because some software vendors provide binary files only to protect their intellectual property.
In this case, the '[patchelf](https://github.com/NixOS/patchelf)' package is helpful to us to modify
the dynamic linker (ELF interpreter) and RPATH of ELF executables and libraries as an workaround.
* What for?
* Change the dynamic loader ("ELF interpreter") of executables
* Change the RPATH of executables and libraries
* Remove declared dependencies on dynamic libraries (DT_NEEDED entries)

[Android/ARM64] Deployment: Manipulating ELF files with patchelf

---

meson.build
native/example_speech_command_tensorflow_lite/meson.build

Relates to https://github.com/nnsuite/nnstreamer/issues/1107.
In order to provide a proper build dependency on nnstreamer-dev for the examples implementing custom filters, this patch modifies meson build scripts.
Signed-off-by: Wook Song <wook16.song@samsung.com>
2. Run test: [ ]Passed [ ]Failed [X]Skipped

[Meson] bugfix: Provide proper build dep for custom filter exmaples

---

android/example_app/README.md

This commit is to improve the instruction guide  to build the NNStreamer SSD application.
It aims to help Android application programmers that do not have the in-depth knowledge
on Gstreamer, Android internals, and operation structure between C/C++ and Java.
**Changelog
1. Added step-by-step manual to reproduce with drag and drop style on console
2. Updated layout of the sections to improve readability
3. Added "what is what" by appending a goal of each section
4. Replaced with file paths with full paths for readability
5. Added how to put the SSD network model files in their own Android device
6. Updated prerequisites
7. Fixed typos

Android: improved the manual of NNStreamer SSD application

---

android/example_app/nnstreamer-multi/build.gradle
android/example_app/nnstreamer-ssd/build.gradle

This commit is to update the existing "defaultconfig" block in build.gradle
file for registering the applications at Google Store.
**Changelog**
- Changed 'minSdkVersion' from 24 to 26
- Keep the unique 'applicationId'
---

Android: Update defaultconfig of build.gradle for google store

---

debian/control

This tries to resolve:
ERROR: Could not detect Ninja v1.5 or newer
of nnstreamer-example build.
This is expected to eliminate CI errors of #57, #58 after rebase.
Signed-off-by: MyungJoo Ham <myungjoo.ham@samsung.com>

[Dist/Debian] Add explicit dependency on ninja >= 1.5

---

native/example_decoder_image_labelling/nnstreamer_example_decoder_image_labelling.c
native/example_image_classification_caffe2/nnstreamer_example_image_classification_caffe2.c
native/example_image_classification_tflite/nnstreamer_example_image_classification_tflite.c
native/example_object_detection_tensorflow/nnstreamer_example_object_detection_tf.cc
native/example_object_detection_tensorflow_lite/nnstreamer_example_object_detection_tflite.cc
native/example_speech_command_tensorflow_lite/nnstreamer_example_speech_command_tflite.c
native/example_two_tensor_stream/nnstreamer_example_two_tensor_stream.c

1. set logging level to g_critical().
2. unify the error messsages.
related issue: #60 

[CodeClean] unify the behavior that appears when there is no appropriate model

---

templates/README.md
templates/tensor_filter_subplugin/deploy.sh
templates/tensor_filter_subplugin/meson.build
templates/tensor_filter_subplugin/packaging/tensor-filter-TEMPLATE.manifest
templates/tensor_filter_subplugin/packaging/tensor-filter-TEMPLATE.spec.in
templates/tensor_filter_subplugin/src/tensor_filter_subplugin.c

This is a template & code-gen for tensor_filter
static in/out tensor dimension subplugin.
Use deploy.sh in the given path to start
your own tensor-filter subplugin code.
To use the template:
1. Go to the template directory
```
$ cd templates/tensor_filter_subplugin
```
2. Deploy (create a new git repo for your subplugin)
```
$ deploy ${NAME} ${GIT_PATH}
$ # Then you have your template code placed at ${GIT_PATH}
$ cd ${GIT_PATH}
${GIT_PATH}$ # here, you can try gbs build.
${GIT_PATH}$ gbs build
...
${GIT_PATH}$ # You get an "empty" tensor-filter subplugin as a Tizen rpm package.
```
3. Write your subplugin with the template
```
${GIT_PATH}$ vi src/tensor_filter_subplugin.c
```
4. Now you are ready to go!
Signed-off-by: MyungJoo Ham <myungjoo.ham@samsung.com>
This resolves the second part …

Template for tensor_filter static in/out dims.

---

README.md
android/README.md

This patch fixes typo in README.md
souce -> source, dfault -> default

Correct typo in README files

---

bash_script/example_models/get-model.sh

Related to #69 
To support tflite image segmentation example,
add option named 'image-segmentation-tflite' at get-model.sh.
Signed-off-by: Jihoon Lee <ulla4571@gmail.com>

[Model] Script to get tflite image segmentation model

---

bash_script/example_image_segmentation_tensorflow_lite/gst-launch-image-segmentation-tflite.sh
bash_script/example_image_segmentation_tensorflow_lite/meson.build
bash_script/meson.build

Related to #69
This PR contains two commits.
1. Bash script example for tflite image segmentation
-  It gets image from webcam and paints regions of objects detected. (* webcam is necessary)
2. Meson build for tflite image segmentation example
- Change related `meson build` for example
Signed-off-by: niklasjang niklasjang@gmail.com
Signed-off-by: Jihoon Lee ulla4571@gmail.com

[Bash/Sample] Bash script example for tflite image segmentation @open sesame 11/15 15:43

---

templates/tensor_filter_subplugin/meson.build

The subplugin name should comply with the tensor-filter rules.
Signed-off-by: MyungJoo Ham <myungjoo.ham@samsung.com>

Fix / Code Template & Gen for tensor-filter subplugins

---

Tizen.native/SingleSample/src/nnstreamer-sample-single.c
native/example_sink/nnstreamer_sink_example.c

update example to set the dimension for text input.
developer should set the input byte size of text input with the property input-dim.

dimension to handle text input

---

templates/tensor_filter_subplugin/src/tensor_filter_subplugin.c

From NNStreamer 1.4.0, tensor-filter API has been updated.
This supports both 1.4.0+ and pre-1.4.0
Signed-off-by: MyungJoo Ham <myungjoo.ham@samsung.com>

Template/Codegen: NNStreamer 1.4.0 support

---

Tizen.platform/Vivante_pipeline_NonGUI_inceptionV3/README.md
Tizen.platform/Vivante_pipeline_NonGUI_inceptionV3/packaging/vivante-inceptionv3-pipeline.spec
Tizen.platform/Vivante_single_NonGUI_inceptionV3/README.md
Tizen.platform/Vivante_single_NonGUI_inceptionV3/packaging/vivante-inceptionv3-single.spec

`vivante-nnstreamer-filter-inceptionv3` is not used anymore

[Tizen.platform] fix the Requires of vivante sample apps

---

bash_script/example_models/get-model.sh

It fixes resource download url.
check: https://github.com/nnsuite/testcases/raw/master/DeepLearningModels/tensorflow-lite/ssd_mobilenet_v2_coco

Fix download url in get-model.sh

---

native/example_speech_command_tensorflow_lite/nnscustom_speech_command_tflite.c

The dimension information for the second tensor of ouput is not fully filled. This patch fills the dimesion information for the dimensions, 2, 3, and 4.
Signed-off-by: Wook Song <wook16.song@samsung.com>
Resolves: Bug realted to speech_command_tflite in https://github.com/nnsuite/nnstreamer/issues/2145

[Native/SpeechCommand] Add omitted dimension information for output

---

debian/control

Section field is necessary to upload package on ppa.
Related issue : https://github.com/nnstreamer/nnstreamer/issues/2271
Refetence link : https://www.debian.org/doc/debian-policy/ch-archive.html#sections

[Debian] Add section for launchpad upload

---

debian/postinst
debian/prerm

After install `nnstreamer-example` debian package, users should manually install model
files using get-model.sh command. Moreover, some examples does not show
detailed error message and it makes users embarrassed as below.
```bash
$ python3 /usr/lib/nnstreamer/bin/nnstreamer_example_image_classification_tflite.py
ERROR:root:cannot find tflite model [/usr/lib/nnstreamer/bin/tflite_model_img/mobilenet_v1_1.0_224_quant.tflite]
Traceback (most recent call last):
File "/usr/lib/nnstreamer/bin/nnstreamer_example_image_classification_tflite.py", line 239, in <module>
example = NNStreamerExample(sys.argv[1:])
File "/usr/lib/nnstreamer/bin/nnstreamer_example_image_classification_tflite.py", line 57, in __init__
raise Exception
Exception
```
This patch automatically downloads all required models …

[Dist/Debian] Add postinst and prerm script for example models

---

native/meson.build

This commit is fix unexpected build issue in Tizen (gbs)
Let's append the example_repo_custom_easy after sending SR to review.tizen.org
---

meson: Disable example_repo_custom_easy

---

Tizen.native/ObjectDetection/src/main.c

[Problem] If all privileges are allowed before, pipeline and view are
not created.
[Solution] init_pipeline and view_create if allowed_count ==
privileges_count

[Tizen.native] Init if all privileges are allowed  @open sesame 06/22 20:51

---

android/example_app/README.md

This patch moves the description for `capi-sample` up, to avoid
some confusion.
When people build the `example_app` project, `capi-sample` is also
automatically compiled. So, they need to configure `capi-sample` too.
Signed-off-by: Dongju Chae <dongju.chae@samsung.com>

[README] Change the order of the description for capi-sample

---

Tizen.platform/Tizen_IoT_text_classification_NonGUI/res/MANIFEST
Tizen.platform/Tizen_IoT_text_classification_NonGUI/res/meson.build
Tizen.platform/Tizen_IoT_text_classification_NonGUI/src/nnstreamer_tizen_iot_text_classification.c

Add nnfw as an option for text classification on Tizen IoT
Notes: text classification requires nnfw version 1.6.0 or more.
Currently, Tizen is providing nnfw 1.4.0, but it will be upgraded to 1.7.0 next week.

    [Tizen/IoT] Add nnfw as a option for text classification

---

native/example_decoder_image_labelling/nnstreamer_example_decoder_image_labelling.c

In this example,
"gboolean running" in "AppData" is not used,
so remove it.
1. Build test: [*]Passed [ ]Failed []Skipped
2. Run test: [ ]Passed [ ]Failed [*]Skipped

[native] Remove unused flag

---

bash_script/example_image_segmentation_tensorflow_lite/gst-launch-image-segmentation-tflite.sh

**before**
**after**
This patch makes the gst-launch image segmentation example looks more completed by adding three things:
* Remove the background checker pattern.
* Set sync=false for videosink to improve responsiveness of the result.
* Remove the letterbox. By the limitation of the model, the model tries to sement against the black letterbox too but it is hard to prevent it using available options in gst-launch-1.0. So it is simpler just to cut the result image.
One potential problem is that the original video isn't guaranteed to have a 16/9 ratio but it is a safe bet because most webcams have 16/9 ratio by default.
---
This change is [<img …

[Bash/Example/Segmentation] Improve visuals and performance

---

debian/control

Since tensorflow for arm arch is not distributed, let's exclude it from debian packaging.
*NNStreamer-example package tested here: https://launchpad.net/~gichan-jang/+archive/ubuntu/ppa-build-test

[Dist/debian] Exclude tensorflow for arm arch

---

Tizen.platform/Tizen_IoT_text_classification_NonGUI/src/nnstreamer_tizen_iot_text_classification.c

In this example, I found a spelling error.
"g_print ("e.g) $ ./nnstreamer_tien_iot_text_classification server tensorflow-lite 192.168.1.1 5001 (optional)nnfw\n");"
I modified "tien" to "tizen".
Signed-off-by: HyesuAhn <linim@naver.com>

[Tizen/IoT] Modifiy spelling error

---

Tizen.platform/Tizen_IoT_ImageClassification/src/nnstreamer_tizen_iot_image_classification.c

Fix typo in Tizen.platform ImageClassification example.
"nnstreamer_tien_iot_image_classification" => "nnstreamer_tizen_iot_image_classification"
Signed-off-by: JeonChangMin <imsameperson@gmail.com>

[Tizen/platform] fix typo in Tizen.platform ImageClassification

---

Tizen.native/SingleSample/inc/nnstreamer-sample-single.h
Tizen.native/SingleSample/src/nnstreamer-sample-single.c

https://github.com/nnstreamer/nnstreamer/issues/2588
[Finding 8](https://lfscanning.org/reports/lfai/nnstreamer-2020-06-02-db85d4bf-ad70-4abf-80a6-d52dd1f6f3f1.html)
changed license to LGPL-2.1
nnstreamer-example/Tizen.native/SingleSample/inc/nnstreamer-sample-single.h
nnstreamer-example/Tizen.native/SingleSample/src/nnstreamer-sample-single.c
Signed-off-by: HyesuAhn <linim@naver.com>

[Tizen/Native]change license to LGPL-2.1

---

android/example_app/api-sample/src/main/java/org/nnsuite/nnstreamer/sample/MainActivity.java

Fix Android API samples, remove invalid method call while running the samples in timer.

[Android] remove unnecessary method

---

README.md

Since `nnstreamer-example` package moved to nnstreamer ppa.
Fix a quick start guide.

[README] Fix quick start guide

---

android/example_app/nnstreamer-media-ssd/jni/nnstreamer-jni.c
android/example_app/nnstreamer-multi/jni/nnstreamer-jni.c
android/example_app/nnstreamer-ssd-autocapture/jni/nnstreamer-jni.c
android/example_app/nnstreamer-ssd/jni/nnstreamer-jni.c
android/example_app/nnstreamer-ssd/res/layout/main.xml
android/multi_device_shared_lib/jni/NNStreamerMultiDevice.c

1. release native window handle when initializing same surface.
2. remove duplicated expose function.

[Android] native window handle

---

Tizen.NET/OrientationDetection/OrientationDetection/OrientationDetection.Tizen.Wearable/OrientationDetection.Tizen.Wearable.csproj
Tizen.NET/OrientationDetection/OrientationDetection/OrientationDetection.Tizen.Wearable/tizen-manifest.xml
Tizen.NET/OrientationDetection/OrientationDetection/OrientationDetection/OrientationDetection.cs
Tizen.NET/OrientationDetection/OrientationDetection/OrientationDetection/OrientationDetection.csproj
Tizen.native/OrientationDetection/.project
Tizen.native/OrientationDetection/.tproject
Tizen.native/OrientationDetection/project_def.prop
Tizen.native/OrientationDetection/tizen-manifest.xml

For wearable sample app OrientationDetection
.NET APP
- Set Tizen .NET API level to 8 (tizen 6.0)
- Update Tizen sdk version
Native APP
- Set target profile to wearable 6.0

[NET/wearable] Update Tizen SDK version and API level

---

native/example_pose_estimation_tflite/README.md
native/example_speech_command_tensorflow_lite/nnstreamer_example_speech_command_tflite.c

Signed-off-by: shortcipher3 <chris.jon.hall@gmail.com>
---
Summarize changes in around 50 characters or less
In the speech command example the device used for recording audio is hard-coded (`alsasrc device="hw:2"`) this program should probably use the `"default"` device or at minimum allow the users to specify their device of choice in the cli.
The ppa `nnstreamer-example` repository contains pre-compiled examples, so it is unexpected for one of the examples to have a hardcoded audio device that is not available on most hardware.
**Changes proposed in this PR:**
- Allow `nnstreamer_example_speech_command_tflite` to take an argument, the audio device 
**How to evaluate:**
1. `./nnstreamer_example_speech_command_tflite default`

alsa device should be configurable for speech_command example

---

Tizen.platform/Vivante_pipeline_NonGUI_inceptionV3/packaging/vivante-inceptionv3-pipeline.spec
Tizen.platform/Vivante_pipeline_NonGUI_yoloV3/CMakeLists.txt
Tizen.platform/Vivante_pipeline_NonGUI_yoloV3/packaging/vivante-yolov3-pipeline.spec
Tizen.platform/Vivante_pipeline_NonGUI_yoloV3/src/main.c
Tizen.platform/Vivante_pipeline_experiments/packaging/vivante-pipeline-experiment.spec
Tizen.platform/Vivante_single_NonGUI_inceptionV3/packaging/vivante-inceptionv3-single.spec

This patch fixes the compile-time errors. Detailed items are as below.
* Add omitted headers
* Fix the wrong option for open() system call
* Update the package name for ML APIs
* Use pkg-config instead of fixed CFlag options.
Signed-off-by: Sangjung <sangjung.woo@samsung.com>

[Native] Fix the compile-time error

---

android/example_app/style-transfer-with-nnstreamer-java-api/src/main/java/org/nnsuite/nnstreamer/sample/MainActivity.java
android/example_app/use-camera-with-nnstreamer-java-api/src/main/java/org/nnsuite/nnstreamer/sample/MainActivity.java

There are two major problems in example projects.
1. Registration of `setPreviewCallback` was not worked in my recent Android10 device. I fixed it to register callback immediately after setting the preview display.
2. Current gstreamer pipeline in `style-transfer-with-nnstreamer-java-api` causes `E/GStreamer+videoconvert: 0:00:01.553407343 0x7c60d44de0 ../gst/videoconvert/gstvideoconvert.c:618:gst_video_convert_set_info:<videoconvert1> input and output formats do not match` error in GStreamer 1.20.0. I don't know the exact reasons but after I removed `videoconvert` in the pipeline, it worked well.
4. Run test: [ ]Passed [ ]Failed [* ]Skipped

[Example] Fix java api examples @open sesame 4/25 12:38

---

bash_script/example_join/gst-launch-join.sh

Set sync to false of the join example to avoid a lot of buffer drop.
1. Build test: [* ]Passed [ ]Failed [ ]Skipped
2. Run test: [* ]Passed [ ]Failed [ ]Skipped

[Join] Set sync to false. @open sesame 07/25 11:07

---

debian/control

We are dropping tensorflow 1.x support.
Make it optional so that older releases can keep building with TF 1.x and newer releases can drop TF 1.x and use TF 2.x instead.
This is required for Ubuntu 22.04 support: https://github.com/nnstreamer/nnstreamer/issues/4088

[debian] Make tensorflow1 optional.

---

native/example_filter_performance_profile/nnstreamer_example_filter_performance_profile.c

From GStreamer 1.20, gst_element_get_request_pad is deprecated. Check the version of GStreamer and use newer API if it's >= 1.20.
Refer: https://gstreamer.freedesktop.org/documentation/gstreamer/gstelement.html?gi-language=c#gst_element_request_pad_simple
Fixes https://github.com/nnstreamer/nnstreamer/issues/4088

Support GStreamer >= 1.20

---

native/example_video_crop/README.md
native/example_video_crop/meson.build
native/example_video_crop/nnstreamer_example_video_crop_tflite.cc
native/meson.build

Example for Tensor_crop plugin which crops the input video from v4l2src and renders the cropped video using autovideosink. Use a video source with an aspect ratio of 1:1 to avoid distortion. 
It uses the following pipeline:
`gst-launch-1.0 v4l2src ! decodebin ! videoconvert ! videoscale ! video/x-raw, width=640, height=480, framerate=30/1, format=RGB ! videocrop left=170 right=170 top=90 bottom=90 ! tee name=t  t. ! queue leaky=2 max-size-buffers=2 ! tensor_converter ! crop.raw t. ! queue leaky=2 max-size-buffers=10 ! tensor_converter ! tensor_transform mode=arithmetic option=typecast:float32,add:-127.5,div:127.5 ! tensor_filter framework=tensorflow2-lite model=tflite_model/ssd_mobilenet_v2_coco.tflite ! tensor_decoder mode=tensor_region option1=1 option2=tflite_model/coco_labels_list.txt …

[EXAMPLE] tensor_crop example

---

native/example_data_preprocessing_for_training/README.md
native/example_data_preprocessing_for_training/nnstreamer_example_data_preprocessing.c

The old version is only working absolute path, so "./" is not working.
- image path is created internally with user input image dir name
- Modify the guide document

[Example] Modify usage of nnstreamer_example_data_preprocessing

---

native/example_training_offloading/nnstreamer_example_training_offloading.c

Add wait-connection and connection-timeout property to get all training data
**How to evaluate:**
1. Describe how to evaluate in order to be reproduced by reviewer(s).
Add signed-off message automatically by running **$git commit -s ...** command.
$ git push origin <your_branch_name>
```

[nnstreamer_training_offloading] Add wait-connection and connection-timeout

---

debian/control

Remove tensorflow dependency from nns-example package.

[Debian] Remove tf dependency

---

Tizen.native/MNIST_inference_after_training_offloading/README.md
Tizen.native/MNIST_inference_after_training_offloading/receiver/src/receiver.c
Tizen.native/MNIST_inference_after_training_offloading/sender/src/sender.c

- Add setting and start MQTT to md
- API name is changed from ml_remote_service_* to ml_service_remote_*
- bugfix: remove double free, unnecessary free function registered in function ml_option_set
1. Build test: [*]Passed [ ]Failed [*]Skipped
2. Run test: [*]Passed [ ]Failed [* ]Skipped

[Example] ml service API name is changed

---

Tizen.web/ImageClassificationOffloading/js/main.js

This patch moves dispose function and adds timeout to fix bug.

[Tizen/Web] Move dispose function and add timeout

---

Tizen.web/ImageClassificationOffloading/index.html
Tizen.web/ImageClassificationOffloading/js/main.js
Tizen.web/ImageClassificationOffloading/js/utils.js

- Create utility module
- Functionalization of duplicated part
- Remove unused variables
- Change var variables to use let type
- Declare variables closer to where they are used

[Tizen/Web] Refactoring ImageClassificationOffloading example

---

Tizen.native/llama_68M.cpp/README.md

- Add a README file to guide users to build/run the pipeline example.

Add a README for llama subtitle sumerizer pipeline example

---

Tizen.web/ImageClassificationOffloading/js/main.js
Tizen.web/ImageClassificationOffloading/js/utils.js
Tizen.web/ImageClassificationPipeline/js/main.js
Tizen.web/ImageClassificationSingleShot/js/main.js
Tizen.web/eslint.config.mjs
Tizen.web/package-lock.json
Tizen.web/package.json

This PR adds eslint config and applies it.

Add eslint for code linting

---

.github/workflows/tizen-web.yml
Tizen.web/ImageClassificationOffloading/js/main.js
Tizen.web/ImageClassificationOffloading/js/utils.js
Tizen.web/ImageClassificationPipeline/js/main.js
Tizen.web/ImageClassificationSingleShot/js/main.js
Tizen.web/eslint.config.mjs
Tizen.web/package-lock.json
Tizen.web/package.json

This patch adds lint check steps in tizen-web workflows.

[After #342] [action] add lint check steps in tizen-web workflows

---

Tizen.web/ImageClassificationOffloadingYolo/js/main.js
Tizen.web/ImageClassificationOffloadingYolo/js/utils.js

This patch applies eslint with fix option and adds some error handling.

Apply eslint to Image Classification Offloading Yolo

---

Tizen.web/ImageClassificationOffloading/js/main.js

This patch changes tensor format from other/tensor to other/tensors. other/tensor is obsoleted.

[Tizen/Web] Use other/tensors in mobilenet

---

.github/workflows/tizen-web.yml

This patch adds step to tizen-web workflow.
ImageClassificationOffloadingService is created to tpk and referenced by wgt.

[action] Add step to create hybrid application 

---

Tizen.web/ImageClassificationOffloading/js/main.js
Tizen.web/ImageClassificationOffloading/js/utils.js
Tizen.web/ImageClassificationOffloadingService/inc/main.h
Tizen.web/ImageClassificationOffloadingService/src/main.c

This patch introduces message port in hybrid application.
Using message port, Tizen native and web application can communicate.

[Tizen] Use message port to communicate

---

Tizen.web/ImageClassificationOffloading/css/style.css
Tizen.web/ImageClassificationOffloading/index.html
Tizen.web/ImageClassificationOffloading/js/main.js
Tizen.web/ImageClassificationOffloading/js/utils.js
Tizen.web/ImageClassificationOffloadingService/src/main.c
Tizen.web/ImageClassificationOffloadingService/tizen-manifest.xml

This patch introduces network service discovery to Tizen service.
NSD will be used to set ip and port automatically.

[Tizen] Introduce network service discovery

---

.github/workflows/tizen-build.yml

This patch adds tizen build native jobs in github action workflows.

[action] add tizen build native and csharp jobs

---

Tizen.native/ml-service-example/sum_and_add_app/src/sum_and_add.c
Tizen.native/ml-service-example/sum_and_add_model_rpk_v1/res/global/sum_and_add/rpk_config.json
Tizen.native/ml-service-example/sum_and_add_model_rpk_v1/res/global/sum_and_add/sum_and_add.pipeline.conf
Tizen.native/ml-service-example/sum_and_add_model_rpk_v2/res/global/sum_and_add/rpk_config.json
Tizen.native/ml-service-example/sum_and_add_model_rpk_v2/res/global/sum_and_add/sum_and_add.pipeline.conf

- Let the `sum_and_add` app use pipeline conf from rpks

[ml-service] Use pipeline conf from rpk

---

bash_script/example_yolo/README.md
bash_script/example_yolo/gst-launch-object-detection-yolov5-onnxruntime.sh
bash_script/example_yolo/gst-launch-object-detection-yolov5-tensorrt10.sh
bash_script/example_yolo/gst-launch-object-detection-yolov5-tflite.sh

---
Added an example for yolov5su using tensorrt
**Changes proposed in this PR:**
- Added tensorrt example
- Updated torchscript example
See also:
https://github.com/nnstreamer/nnstreamer/pull/4482
**How to evaluate:**
1. Run the example for tensorrt.

Add tensorrt example

---

Tizen.web/ImageClassificationOffloading/js/main.js

This patch removes meaningless dicimal points.

[Tizen/web] Use only 3 digits after decimal point
